# Generated by Django 4.1.7 on 2023-03-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_news_banner_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
